### ISSUE TITLE
Dataset Visualizer not showing

### ISSUE THREAD

**Issue by carlokok** [Microsoft/ConcordExtensibilitySamples#26]
When writing a custom debugger the DataSet visualizer doesn't load and says:
- Could not load this custom viewer.

There are no exceptions or errors in the debug output. Is there anything special needed to get that going?

**Comment by plnelson** [comment]
I tried it with the Iris sample and both the DataSet and WPF Tree visualizers are working.  I don't think this is related to the sample, but I'm happy to help you diagnose what's going on.  PM me on gitter and I'll take a look.

**Comment by carlokok** [comment]
That's very odd. We've managed to get things working by adding:

ClrCustomVisualizerVSHost: "{E82F32A8-074E-465A-86E5-D68A87284F61}"

under our registration to get things working (which Isis doesn't need for some reason)

**Comment by plnelson** [comment]
The entire design of UI visualizers is pretty counter-intuitive.  I wasn't involved with the original design, but it appears the that intention was for each language to use it's own visualizer infrastructure.  I don't see this happening though.  You can "borrow" C#'s visualizer framework by setting the reg key you mention.  It worked when I tested it because I used the visualizer from a C# stack frame.  Iris doesn't support any types that would allow a custom visualizer.

I'm closing this issue because it's related to the design of the debugger rather than the sample.
